language: node_js
node_js:
  - "stable"
dist: trusty
sudo: false
cache:
  directories:
  - node_modules
before_script:
  - "npm i -g gatsby eslint"
  - "npm i"
script:
  - "npm run lint"
  - "npm run build"
