[build]
  command = "gatsby build"
  publish = "public/"

[template]
  incoming-hooks = ["Ghost"]

[template.environment]
    SITE_URL = "https://gatsby.ghost.org"
    SITE_TITLE = "Ghost Gatsby Starter"
    SITE_SHORT_TITLE = "Ghost"
    SITE_DESCRIPTION = "A starter template to build amazing static websites with Ghost and Gatsby"

[context.production.environment]
    NODE_ENV = "production"
    PRODUCTION_API_KEY = "YOUR CONTENT API KEY"
    PRODUCTION_API_URL = "https://your-ghost-blog.com"

[context.development.environment]
    NODE_ENV = "development"
    DEVELOPMENT_API_KEY = "YOUR CONTENT API KEY"
    DEVELOPMENT_API_URL = "https://your-ghost-blog.com"
